name : Docker image build and scan with Trivy

on:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout the repo
              uses: actions/checkout@v4

            - name: Install Trivy and scan Filesystem
              uses: aquasecurity/trivy-action@0.31.0
              with:
                scan-type: fs
                scan-ref: ./python-boilerplate
                format: table
                exit-code: 1
                severity: CRITICAL
                scanners: vuln,secret,misconfig

            - name: Set image tag
              id: image-tag
              run: |
                # made available to trivy-action
                echo "image_tag_value=ttl.sh/my-python-app-$(date +%s):2h" >> $GITHUB_OUTPUT

            - name: Build Docker Image
              run: |
                IMAGE_TAG="${{ steps.image-tag.outputs.image_tag_value }}"
                docker build -t $IMAGE_TAG ./python-boilerplate

            - name: Scan Docker Image with Trivy
              if: success()
              uses: aquasecurity/trivy-action@0.31.0
              with:
                scan-type: image
                image-ref: "${{ steps.image-tag.outputs.image_tag_value }}"
                format: table
                exit-code: 1
                severity: CRITICAL
                scanners: vuln,secret,misconfig,license
              env:
                  TRIVY_LOG_LEVEL: debug

            - name: Push Docker Image
              run: |
                IMAGE_TAG="${{ steps.image-tag.outputs.image_tag_value }}"
                docker push $IMAGE_TAG
